### ISSUE TITLE
"No longer works" by Albert Yang, Aug. 2, Brave

### ISSUE THREAD

**Issue by akinuri** [akinuri/download-url-public#1]
The user says the extension (2.0.3) doesn't work on Chrome and Brave (v1.42.97).

**Comment by akinuri** [comment]
I just downloaded the latest version of Brave (1.43.89) and tested the extension. Weirdly, it works. Here's a little proof.

https://user-images.githubusercontent.com/13146977/188870639-1cf7d8de-10a2-417e-b351-712bcc1af4a9.mp4

If a user encounters an issue with the extention, the user can try to be more elaborate about the issue. For example,

* are the inputs in the popup window filled?
* does the download button work?

Since this is a very simple extension, there are only two steps/topics to know about.

To know more about the issue, one can try to inspect the extension to see if there are any errors in the console.

https://user-images.githubusercontent.com/13146977/188871290-f1eb2734-b0d1-4611-a60f-f427bff7b09d.mp4

<hr>

In the current version (2.0.3), there's an error in the console when one does "Inspect popup".

> ```
> Error handling response: TypeError: Cannot read properties of undefined (reading 'replace')
>     at chrome-extension://gkhcppbljnkkjjkahichmbajofmnglic/popup/app.js:79:23
>     at Array.forEach (<anonymous>)
>     at stripInvalidChars (chrome-extension://gkhcppbljnkkjjkahichmbajofmnglic/popup/app.js:77:19)
>     at chrome-extension://gkhcppbljnkkjjkahichmbajofmnglic/popup/app.js:16:28
> ```

I don't think this is related to the mentioned issue, but nevertheless, this will be fixed very soon in v2.0.4
